import "./globals.css";
import { lato } from "./fonts";
import HeaderClient from "@/ui/header/HeaderClient";
import FooterWrapper from "@/ui/footer/FooterWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet" />
      </head>
      <body className={lato.className}>
        <HeaderClient />     
        {children}
        <FooterWrapper />
      </body>
    </html>
  );
}
